completed fetch exercise
LukeYasu/c0824-code-solutions pull request #69
Opened 2024-09-28 18:26 UTC by LukeYasu

<img width="975" alt="Screenshot 2024-09-28 at 11 26 02 AM" src="https://github.com/user-attachments/assets/7211b295-cd0d-4d41-80e5-cc93891d0b12">

2024-09-30 16:04 UTC, shawnkost requested changes
Missing a function here

2024-09-30 16:04 UTC, shawnkost commented on fetch/main.ts
> +fetchData();
You should have 2 different functions for this exercise

2024-10-15 17:30 UTC, RobertGardner approved these changes
Minor comment.

2024-10-15 17:30 UTC, RobertGardner commented on fetch/main.ts
> +      throw new Error(`HTTP Error! Status: ${fetchResponse}`);
This will use `fetchResponse.toString()` in the message, which won't have the status. You should use `fetchResponse.status` instead.

2024-10-15 17:30 UTC, RobertGardner commented on fetch/main.ts
> +      throw new Error(`HTTP Error! Status: ${fetchResponse}`);
Same here.

2024-10-16 17:52 UTC, merged